DROP TABLE IF EXISTS TBL_AIRLINES;



CREATE TABLE TBL_AIRLINES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  initial_budget VARCHAR(250) NOT NULL,
  location VARCHAR(250) DEFAULT NULL
);

--DROP TABLE IF EXISTS AIRLINES;



--CREATE TABLE AIRLINES (
--  id INT AUTO_INCREMENT  PRIMARY KEY,
--  name VARCHAR(250) NOT NULL,
--  initial_budget VARCHAR(250) NOT NULL,
--  location VARCHAR(250) DEFAULT NULL
--);